# ============================================
# GROQ CLIENT
# Fast free LLM via Groq API
# ============================================

from groq import Groq
from app.utils.logger import logger
from config.settings import settings
from config.model_config import GROQ_LLM_CONFIG


# --- Singleton client ---
_groq_client = None


def get_groq_client() -> Groq:
    """
    Get or create Groq client instance.

    Returns:
        Groq client
    """
    global _groq_client

    if _groq_client is None:
        if not settings.GROQ_API_KEY:
            raise ValueError(
                "GROQ_API_KEY not set in .env file. "
                "Get your free key at: https://console.groq.com"
            )

        _groq_client = Groq(api_key=settings.GROQ_API_KEY)
        logger.info(f"✅ Groq client ready: {GROQ_LLM_CONFIG['model']}")

    return _groq_client


def generate_answer(
    system_prompt: str,
    user_prompt:   str,
) -> str:
    """
    Generate answer using Groq API.

    Args:
        system_prompt: System instructions
        user_prompt:   User question + context

    Returns:
        Generated answer string
    """
    client = get_groq_client()

    logger.info(f"🤖 Generating answer with Groq: {GROQ_LLM_CONFIG['model']}")

    response = client.chat.completions.create(
        model      = GROQ_LLM_CONFIG["model"],
        temperature= GROQ_LLM_CONFIG["temperature"],
        max_tokens = GROQ_LLM_CONFIG["max_tokens"],
        messages   = [
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt},
        ]
    )

    answer = response.choices[0].message.content.strip()
    logger.info("✅ Answer generated by Groq successfully")
    return answer